"""Add raw_segments to Transcription model

Revision ID: 01613eda6ed6
Revises: 26a7e4ce401f
Create Date: 2025-08-08 15:58:43.551656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01613eda6ed6'
down_revision: Union[str, Sequence[str], None] = '26a7e4ce401f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcriptions', sa.Column('raw_segments', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcriptions', 'raw_segments')
    # ### end Alembic commands ###
