"use client";

"use client";

import { useRef, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Loader2 } from "lucide-react";
import Link from "next/link";
import { Progress } from "@/components/ui/progress";
import { useTranscribeStore } from "@/lib/stores/useTranscribeStore";
import { useTranscribeApi } from "@/lib/hooks/useTranscribeApi";
import { FileUpload } from "@/components/transcribe/FileUpload";
import { UrlInput } from "@/components/transcribe/UrlInput";
import { TranscriptionResult } from "@/components/transcribe/TranscriptionResult";
import { AudioPlayer } from "@/components/transcribe/AudioPlayer";

export default function TranscribePage() {
  const {
    file,
    url,
    transcription,
    processedTranscription,
    audioUrl,
    isLoading,
    isProcessing,
    error,
    progress,
    progressMessage,
    estimatedTime,
    setFile,
    setUrl,
  } = useTranscribeStore();
  const { handleSubmit } = useTranscribeApi();
  const resultCardRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if ((transcription || error) && resultCardRef.current) {
      resultCardRef.current.scrollIntoView({ behavior: "smooth", block: "center" });
    }
  }, [transcription, error]);

  return (
    <div className="p-6 min-h-screen flex flex-col items-center">
      <div className="w-full max-w-4xl">
        <div className="flex justify-between items-center mb-6">
          <h1 className="text-3xl text-gray-800 dark:text-white">Transcribe Audio</h1>
          <div className="flex gap-2">
            <Link href="/history">
              <Button variant="outline">View History</Button>
            </Link>
            <Link href="/">
              <Button>Back to Chatbot</Button>
            </Link>
          </div>
        </div>
        <Card className="w-full">
          <CardHeader>
            <CardTitle>Upload Audio File or Provide URL</CardTitle>
          </CardHeader>
          <CardContent className="flex flex-col gap-6">
            <FileUpload file={file} onFileChange={setFile} />
            <UrlInput url={url} onUrlChange={setUrl} />
            {isLoading ? (
              <div className="flex flex-col items-center gap-2">
                 <Progress value={progress} className="w-full" />
                 <p className="text-sm text-muted-foreground">{progressMessage}</p>
                 {estimatedTime && (
                   <p className="text-xs text-muted-foreground">
                     (Estimated time: ~{Math.ceil(estimatedTime / 60)} minutes)
                   </p>
                 )}
               </div>
            ) : (
              <div className="mt-6 flex justify-center">
                <Button onClick={handleSubmit} disabled={!file && !url}>
                  Transcribe
                </Button>
              </div>
            )}
          </CardContent>
        </Card>
        <div className="w-full max-w-4xl mt-4 text-center">
          <p className="text-xs text-gray-500 dark:text-gray-400">
            Please note: This transcription is generated by an AI and may contain inaccuracies. Names and technical terms can sometimes be misinterpreted.
          </p>
        </div>
        {audioUrl && (
          <div className="my-6">
            <AudioPlayer src={audioUrl} />
          </div>
        )}
        <div ref={resultCardRef}>
          <TranscriptionResult />
        </div>
        <div className="h-96" />
      </div>
    </div>
  );
}